### ISSUE TITLE
Specified module could not be found

### ISSUE THREAD

**Issue by shekharkhatri** [KnicKnic/go-powershell#10]
I am trying to check if a windows feature is enabled or not. Below is the code used as per the example shown in the documentation.
However, the binary could not run as the error says module could not be found. Based on quick research, it seems like some dll file is missing. Did I miss any steps?
![image](https://user-images.githubusercontent.com/44218196/92326067-1e620d80-f06f-11ea-9148-e64a785fa36a.png)
![image](https://user-images.githubusercontent.com/44218196/92326050-04282f80-f06f-11ea-81a5-d7c144bbeac4.png)

**Comment by KnicKnic** [comment]
Did you add psh_host.dll. In the future I’ll ship this in the binary itself. https://github.com/KnicKnic/go-powershell#dependencies

**Comment by shekharkhatri** [comment]
Thanks @KnicKnic . Seems like I missed the dependencies part. Working now. Cheers!
