### ISSUE TITLE
Issues when building API for Linux with this package

### ISSUE THREAD

**Issue by sagarkvs** [KnicKnic/go-powershell#12]
I am seeing issues for this package when doing build in Linux from windows platform.

I have set the GOOS=Linux & GOARCH=amd64 but still I am seeing issues with it.

go : ..\src\github.com\KnicKnic\go-windows\pkg\kernel32\kernel32.go:7:2: build constraints exclude all Go files in C:\Users\kvenka201\Documents\GoProjects\JarvisDBA\src\golang.org\x\sys\windows
At line:1 char:1
+ go build .\main.go
+ ~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (..\sr...g\x\sys\windows:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError

**Comment by KnicKnic** [comment]
This package does not support linux.

**Comment by KnicKnic** [comment]
Closing as this is stated in the first sentence of the Goal in readme.
