### ISSUE TITLE
Is there way to run command with elevated priveleges?

### ISSUE THREAD

**Issue by ArseniyShestakov** [KnicKnic/go-powershell#9]
Hello and thanks for this very useful package. I'm not exactly a great Go programmer and I only use Windows when I have to so I have small question regarding your package.

Is there some easy way to run elevated powershell command without elevating my go app process?

I have found another example for PS in go here, but I guess there no solution for elevating:
https://gist.github.com/coolbrg/d1854cc771025efb4a30197820c2c612

If you can give me some directions I might be able to implement it and contribute it back. Thanks!

**Comment by KnicKnic** [comment]
I don't have this problem due to always running the hosting process already elevated. Could you just elevate your process before calling into powershell?

**Comment by ArseniyShestakov** [comment]
I would rather not to keep extra privileged process running in the background. I wanted to do some CA root certificate management magic for my machine and supposed powershell for that, but end up just using certutil instead.

**Comment by ArseniyShestakov** [comment]
In any case this isn't some kind of problem with your lib since communication between processes running with different privileges is well beyond the scope. I guess the right way would be just run separate go app with elevated process privileges that will in term use powershell. Then I can just communicate between them over network or shared memory.

So yeah I guess I'll close this one since I did not manage to find a proper way to implement it in Go.
